title: "L'analista imperfetto"
tagline: "La Stanza dei Bottoni: Mercati, geopolitica e trend senza filtri"
description: "Analisi indipendente su mercati, geopolitica e macro. Senza filtri."
url: "https://alessandromartelli.github.io"
author: "Alessandro Martelli"
email: "info@tuosito.it"

markdown: kramdown
permalink: /:year/:month/:day/:title/

exclude:
  - README.md
