title: "L'analista imperfetto"
tagline: "La Stanza dei Bottoni: Mercati, geopolitica e trend senza filtri"
description: "Mercati, geopolitica e macro. Senza filtri."
url: "https://martellialessandro.github.io"
author: "Alessandro Martelli"
email: "alessandro__martelli@libero.it"

markdown: kramdown
permalink: /:year/:month/:day/:title/

exclude:
  - README.md
